  nfa:
    image: reuteras/nfa:latest
    hostname: nfa
    volumes:
      - ./nfa/config.ini:/app/config.ini
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:5001"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 180s
